# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: comunication.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'comunication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63omunication.proto\x12\tmodeldist\"[\n\x0cModelRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12&\n\x06\x66ormat\x18\x02 \x01(\x0e\x32\x16.modeldist.ModelFormat\x12\x0f\n\x07version\x18\x03 \x01(\t\"\x1a\n\nModelChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x9b\x01\n\x0bModelHeader\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12&\n\x06\x66ormat\x18\x02 \x01(\x0e\x32\x16.modeldist.ModelFormat\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x0c\n\x04\x61rch\x18\x04 \x01(\t\x12\r\n\x05\x64type\x18\x05 \x01(\t\x12\x12\n\ntotal_size\x18\x06 \x01(\x04\x12\x0e\n\x06sha256\x18\x07 \x01(\t\"g\n\x0bModelStream\x12(\n\x06header\x18\x01 \x01(\x0b\x32\x16.modeldist.ModelHeaderH\x00\x12&\n\x05\x63hunk\x18\x02 \x01(\x0b\x32\x15.modeldist.ModelChunkH\x00\x42\x06\n\x04part*8\n\x0bModelFormat\x12\x0e\n\nSTATE_DICT\x10\x00\x12\x0f\n\x0bTORCHSCRIPT\x10\x01\x12\x08\n\x04ONNX\x10\x02\x32Q\n\x10ModelDistributor\x12=\n\x08GetModel\x12\x17.modeldist.ModelRequest\x1a\x16.modeldist.ModelStream0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comunication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODELFORMAT']._serialized_start=417
  _globals['_MODELFORMAT']._serialized_end=473
  _globals['_MODELREQUEST']._serialized_start=33
  _globals['_MODELREQUEST']._serialized_end=124
  _globals['_MODELCHUNK']._serialized_start=126
  _globals['_MODELCHUNK']._serialized_end=152
  _globals['_MODELHEADER']._serialized_start=155
  _globals['_MODELHEADER']._serialized_end=310
  _globals['_MODELSTREAM']._serialized_start=312
  _globals['_MODELSTREAM']._serialized_end=415
  _globals['_MODELDISTRIBUTOR']._serialized_start=475
  _globals['_MODELDISTRIBUTOR']._serialized_end=556
# @@protoc_insertion_point(module_scope)
