# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import comunication_pb2 as comunication__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in comunication_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModelDistributorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetModel = channel.unary_stream(
                '/modeldist.ModelDistributor/GetModel',
                request_serializer=comunication__pb2.ModelRequest.SerializeToString,
                response_deserializer=comunication__pb2.ModelStream.FromString,
                _registered_method=True)


class ModelDistributorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelDistributorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetModel': grpc.unary_stream_rpc_method_handler(
                    servicer.GetModel,
                    request_deserializer=comunication__pb2.ModelRequest.FromString,
                    response_serializer=comunication__pb2.ModelStream.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'modeldist.ModelDistributor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('modeldist.ModelDistributor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelDistributor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/modeldist.ModelDistributor/GetModel',
            comunication__pb2.ModelRequest.SerializeToString,
            comunication__pb2.ModelStream.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
