# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fl.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fl.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x66l.proto\x12\x02\x66l\"\x07\n\x05\x45mpty\"8\n\x0bModelPacket\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05round\x18\x02 \x01(\x05\x12\x0c\n\x04stop\x18\x03 \x01(\x08\"w\n\x0bModelUpdate\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\r\n\x05round\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x13\n\x0bnum_samples\x18\x04 \x01(\x05\x12\x11\n\ttrain_acc\x18\x05 \x01(\x02\x12\x10\n\x08test_acc\x18\x06 \x01(\x02\"\'\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2h\n\x10\x46\x65\x64\x65ratedService\x12,\n\x0eGetGlobalModel\x12\t.fl.Empty\x1a\x0f.fl.ModelPacket\x12&\n\nSendUpdate\x12\x0f.fl.ModelUpdate\x1a\x07.fl.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=16
  _globals['_EMPTY']._serialized_end=23
  _globals['_MODELPACKET']._serialized_start=25
  _globals['_MODELPACKET']._serialized_end=81
  _globals['_MODELUPDATE']._serialized_start=83
  _globals['_MODELUPDATE']._serialized_end=202
  _globals['_ACK']._serialized_start=204
  _globals['_ACK']._serialized_end=243
  _globals['_FEDERATEDSERVICE']._serialized_start=245
  _globals['_FEDERATEDSERVICE']._serialized_end=349
# @@protoc_insertion_point(module_scope)
